### ISSUE TITLE
Editor doesn't appear

### ISSUE THREAD

**Issue by SinisterLuffy5** [TheLazzoro/BetterTriggers#13]
I have been using BetterTriggers for the good past year, but all of a sudden the editor refuses to appear. Taskbar indicate that the program is active, but clicking its button did nothing.
![Test](https://github.com/user-attachments/assets/1fdf67bb-0caf-4df3-930e-5c0035e5ff0e)

**Comment by TheLazzoro** [comment]
It could be because it has positioned itself outside the bounds of your screen. It can happen if you unplug a monitor for example.
You can try and delete the settings.json file in your `...AppData\Local\Better Triggers\` folder, then launch again

**Comment by SinisterLuffy5** [comment]
That did the trick! Thank you!
